### ISSUE TITLE
Typos/Errors in Stat Requirements

### ISSUE THREAD

**Issue by loweml** [AT41/StatRequirementChecklist#1]
Your plugin is a fantastic addition to OpenRCT2, but you've made typos with the max speeds. I'm using the Marcel list [https://www.reddit.com/r/LordMarcel/comments/78maqk/rct2_table_with_the_minimum_stat_requirements_for/](here) for these values. 

It looks like you saw, for example, 42 km/h on the Bobsleigh coaster, mistook it for mph, and converted it to km/h, since 42 mph ≈ 67 km/h. Should be an easy fix and a huge improvement to your plugin.

**Comment by AT41** [comment]
Thanks for logging the issue! The issue was that the formatter for velocity expects the units to be in imperial, which is strange because it expects the length to be in metric... Since the formatter only accepts integers, the requirements for max speed will sometimes be 1 unit higher than what it should be due to rounding errors; Fixing this will require modifying the API for OpenRCT2 itself, but the bandaid fix I've made should hopefully be sufficient enough.

**Comment by loweml** [comment]
Do you have the compiled version, and not just the source code?

**Comment by AT41** [comment]
Sorry about that! I've attached the compiled plugin and re-released it. I also took a revisit and figured out a workaround for the rounding issues, so there shouldn't be any stat requirements that are wrong. Thanks for reporting!
